### ISSUE TITLE
QA #1 - CCRP MVP - Netz Zero Planning Bugs

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#11]
- 1. La courbe "fait n'importe quoi" 
- 2. Manque les années en abscisse
- 3. Le hover ne fonctionne pas

<img width="1365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDV0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--842f4ff98d98283f5a54ed0d4d8caa4617964306/image.png" alt="image.png" />

**Comment by schwepps** [comment]
1. Probably a data issue
2. Will check on frontend
3. Will check on frontend

**Comment by schwepps** [comment]
2 => Fixed
3 => No issue works correctly
