### ISSUE TITLE
QA #1 - CRP MVP - Stock - Annual

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#13]
1. les années sont dans le désordre
2. Devrait y avoir des Ex-post achetés (le projet braulio)
3. La pagination fonctionne pas => Quand on clique sur 2, cela load puis revient sur la page 1, et idem pour 3 ou 4

<img width="1152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZ0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62d15c4351464aebcc7f95193574ebb2ad407d4c/image.png" alt="image.png" />

**Comment by schwepps** [comment]
1 and 2 => Need to be fixed on backend.
3. Same global pagination issue.
