### ISSUE TITLE
QA#1 - CRP MVP - Financial Analysis

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#14]
Average issued Price remains TBD

<img width="465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEp1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34ae902f03050b3ab7c543331099f9e43e5504fa/image.png" alt="image.png" />

**Comment by schwepps** [comment]
Value is missing in the graphQL query. Need to be added on backend and mapped on frontend when available.
