### ISSUE TITLE
QA#1 - CRP MVP - BU Project Metrics 

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#15]
Project metrics are broken: 

Color should be green 100%
Project standard should be Verra 100% 
Madagascar should be 100% 

<img width="1305" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFp1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96e73f2aae07e6631daf09683033def8b57a535d/image.png" alt="image.png" />

**Comment by schwepps** [comment]
Need to be fixed on backend.

**Comment by G2CARBZ** [comment]
Actually since then I have also allocated 100 Banegas units. 
So there should be a slight percentage of ERS as well, and slight percentage of Costa Rica, and 100% green still
