### ISSUE TITLE
QA#1 - CRP MVP - BU Impact Metrics

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#16]
Impact metrics broken

Removed tons - not working
Restored hectares - not working
Protected species - not working

<img width="1692" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGh1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--499ac4a9ba2b53e48597def0c4661735d06fa845/image.png" alt="image.png" />

**Comment by schwepps** [comment]
Need to be fixed on backend.

**Comment by MartianGreed** [comment]
done
