### ISSUE TITLE
QA#1 - CRP MVP - Impact Reports link

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#17]
None of the impact reports link is working. 
Neither at the business unit level
Nor at the menu level 
Nor at the project level

**Note to myself => list of relevant links to provide**

**Comment by schwepps** [comment]
Waiting for links to complete #7

**Comment by G2CARBZ** [comment]
Global link (the one in the menu + the one at the Group business Unit level): https://carbonable.sextan.app/public/global/custom/jqnk50pr511dah162

- Braulio Carrillo Project link: https://carbonable.sextan.app/public/report/project/mjpigwpr519dah162
- Bokpyn-Karathuru Project link: https://carbonable.sextan.app/public/report/project/cor2fkpr518dah162
- Manjarisoa Project link: https://carbonable.sextan.app/public/report/project/7738fmpr517dah162
- Las Delicias Project Link: https://carbonable.sextan.app/public/report/project/zulohdpr516dah162
- Chaco Agroforestry Project Link: https://carbonable.sextan.app/public/report/project/71e7sbpr515dah162
- Banegas Farm Project Link: https://carbonable.sextan.app/public/report/project/unfmb7pr514dah162

**Comment by schwepps** [comment]
@MartianGreed can you add these url in the projet query? Same as we did for images.
I will add the global ones in directly in the code for now.

**Comment by MartianGreed** [comment]
done

**Comment by G2CARBZ** [comment]
None works.
All links go to https://carbonable.sextan.app/ instead

**Comment by schwepps** [comment]
Seems to work on the deployed version.
