### ISSUE TITLE
QA#1 - CRP MVP - Reporting (dashboard)

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#18]
1. SDGs broken (should only but a list of all applicable project SDGs)
2. t an hectares semblent être inversés

3. => nous devons nous accordé sur la manière de calculer les KPIs:
- a. tous projets confondus? 
- b. la totalité de ceux alloués? 
- c. ou seuls ceux vraiment planifiés pour offset? 

à discuter ensemble

<img width="1259" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUp1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--104f2b9cafc510603101b5dd1eb58a54de7ef8bc/image.png" alt="image.png" />

**Comment by schwepps** [comment]
1 and 2 will be fixed on backend.
3. Need to be the sum of all projects. Otherwise it will be for all projects for SDGs and Protected Species and something else for removed tons and restaured hectares. And anyway, even if it's not allocated, the carbon will be removed and the forest restaured.
