### ISSUE TITLE
QA#1 - CRP MVP - PROJECT HEADERS

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#19]
1. L'allocation ne fonctionne pas... Sur manjarisoa: factuellement, 100 000 units sont alloués et non la totalité. 
2. Attention l'allocation est en kg et non en tonnes 
3. Sur banegas farm, il devrait y avoir des ex-posts de dispos et là, cela reste à zéro. 
4. Certaines images ne loadent pas (e.g. Manjarisoa)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXR1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a01b557fced6b1a0af065646b6c70d46daec1765/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXh1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da938456d43349bf856b6d13a9310a04b99a5e40/image.png" alt="image.png" />

**Comment by schwepps** [comment]
1. Allocation on backend works in % and in tons on frontend. Will fix frontend for now to allocate in %.
2. On n'a pas compris.
3. Config issue
4. Will check image URL on backend.

**Comment by G2CARBZ** [comment]
2. Allocation units sur manjarisoa: 152727000 => y'a trois zéros de trop (parce que j'imagine que c'est en kg et non en tonnes)
