### ISSUE TITLE
QA#1 - CRP MVP - Project Impact

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#20]
Exemple concret de banegas farm
1. les SDGs ne matchent pas
2.  le # de species ne matche pas 
3. le nombre de t ne matche pas
4. le nombre d'hectares ne matche pas

<img width="1152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZ1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e61b646429b12bffce32e732e0ac4309a5cbdcb/image.png" alt="image.png" />

**Comment by schwepps** [comment]
Need to fix on backend.

**Comment by MartianGreed** [comment]
done
