### ISSUE TITLE
QA#1 - CRP - MVP - Rajouter Rating dans le template et les projets individuels

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#21]
Rating est une info dans le header des projets qui n'est pour l'instant pas dans le template projet 
+ à rajouter dans la checklist github

=> pour moi
=> pour Arnaud 

+ notifier valentin lorsque les projets individuels ont eu les notes ajoutées (pour loader les bonnes)

<img width="1872" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjF1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66b8f76d7dc5520988d0b056f234691766bf3fa5/image.png" alt="image.png" />

**Comment by G2CARBZ** [comment]
@cloudvenger => done on the template file https://docs.google.com/spreadsheets/d/100tnVcU4yBEIR4w-9tefp4OXCRivgTd8Y-wA-FhsRPg/edit#gid=1291949267

Du coup j'ai ajouté "Risk Analysis" dans Generic et "Impact Report Link" dans Tech 

=> à rajouter côte check list dans le github

**Comment by cloudvenger** [comment]
done her : https://github.com/Carbonable/carbonable-metadata/blob/main/.github/ISSUE_TEMPLATE/new-tokenized--projects-.md
