### ISSUE TITLE
QA#1 - CRP MVP - Project Allocation 

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#22]
J'ai alloué 100 t de banegas farm à la Business Unit "Group"

1. rien ne se passe quand je clique sur yes. Mais quand je reload, l'allocation est bien prise en compte. 

2. Je vois que l'allocation de 100 est bien prise en compte dans carbon management, mais dans le header rien n'a changé au niveau des available ex-ante. 

<img width="1872" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1J1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e700d6bf356ba51479f763d45ee7d513f1149b3f/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1Z1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c35b98892e33e7a2c6414e0a27b8887b7667394f/image.png" alt="image.png" />

**Comment by schwepps** [comment]
1. Need to refetch auto
2. Need to fix on backend.

**Comment by schwepps** [comment]
Auto refetch done

**Comment by MartianGreed** [comment]
done
