### ISSUE TITLE
Hover info not correct - let's add a couple of indicators

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#27]
CO2 contributions are wrong 

Hover information should be
- Carbon Emissions     
- Credits Retired          (I.e. the qty of credits consumed this very year)
- Net Zero target         (%)
- Actuals                       (%)

<img width="788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE9rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc98f21966e6f29711ad264ef757a5c43b58eace/image.png" alt="image.png" />

**Comment by schwepps** [comment]
Done for emission, actual and target.
Waiting for instruction from @G2CARBZ for retired.
@MartianGreed we might need to add retired data in the api if confirmed.

**Comment by schwepps** [comment]
Closing as it will be done in #31
