### ISSUE TITLE
CCRP MVP wrap up

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-ccrp-app#31]
### Description
**Graph**
 - [x] Add retired column
 - [x] Add zoom librairy
 
**Business unit allocations**
 - [x] Add Carbonable icon on the card
 
**Reporting**
 - [x] Get new image without Bel from Guillaume
 
**Portfolio**
 - [x] Get new map from Guillaume
 
**Project page**
 - [x] Harmonize the header
 - [x] Add retired column on chart

**Menu**
 - [x] Calculator et Impact Report in i-frame

**Financial Analysis**
 - [ ] Waiting for MVP from Guillaume
 
**Overall**
 - [x] Units in all tables headers
 - [x] Actual in percentage like target

**Comment by schwepps** [comment]
Only calculator in iframe for now. 
Impacter is not configured to accept embbeding.

**Comment by schwepps** [comment]
After last meeting still deed to rework:
- [ ] Financial analysis on dashboard
- [ ] Financial analysis at BU level
- [ ] Stock table at project level

**Comment by Khyati729** [comment]
Create a new Test Ticket @Khyati729

**Comment by schwepps** [comment]
Delta mettre 0 à la place de n/a
Financial Analysis: cannot query purchased_price (check model)
Enlever console.log
