### ISSUE TITLE
Link to impact reports

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-ccrp-app#7]
Je veux des rapports d”impact
- à l’échelle du groupe
- à l’echelle des business units
- à l’échelle des projets

(Lien vers Impactr pour le moment)

**Comment by schwepps** [comment]
@G2CARBZ how do we know the links to share for each level?

**Comment by G2CARBZ** [comment]
For the very MVP there won't be "Business Units" levels 
Simply the group report, and the project reports
As discussed during last scrum => we simply add the link to the overall group impact report : https://carbonable.sextan.app/public/global/custom/k9cewhpr511dah162

**Comment by MartianGreed** [comment]
done on #17
